from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'front-end/login.html'}, name='frontlogin'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': reverse_lazy('frontindex')}, name='frontlogout'),
    url(r'^$', 'izin.views.frontindex', name='frontindex'),
    url(r'^404/', 'izin.views.page_404', name='404'),
    #url(r'^login/', 'izin.views.frontlogin', name='frontlogin'),
    url(r'^tentang/$', 'izin.views.tentang', name='tentang'),
    url(r'^layanan/$', 'izin.views.layanan', name='layanan'),
    url(r'^layanan/siup-pt$', 'izin.views.layanan_siup_pt', name='layanan_siup_pt'),
    url(r'^layanan/siup-koperasi$', 'izin.views.layanan_siup_koperasi', name='layanan_siup_koperasi'),
    url(r'^layanan/siup-cv$', 'izin.views.layanan_siup_cv', name='layanan_siup_cv'),
    url(r'^layanan/siup-perorangan$', 'izin.views.layanan_siup_perorangan', name='layanan_siup_perorangan'),
    url(r'^layanan/siup-pendaftaran-ulang$', 'izin.views.layanan_siup_pendaftaran_ulang', name='layanan_siup_pendaftaran_ulang'),
    url(r'^layanan/siup-perubahan$', 'izin.views.layanan_siup_perubahan', name='layanan_siup_perubahan'),
    url(r'^layanan/siup-pergantian-hilang$', 'izin.views.layanan_siup_pergantian_hilang', name='layanan_siup_pergantian_hilang'),
    url(r'^layanan/siup-pergantian-rusak$', 'izin.views.layanan_siup_pergantian_rusak', name='layanan_siup_pergantian_rusak'),
    url(r'^layanan/ho-permohonan-baru$', 'izin.views.layanan_ho_baru', name='layanan_ho_baru'),
    url(r'^layanan/ho-daftar-ulang$', 'izin.views.layanan_ho_daftar_ulang', name='layanan_ho_daftar_ulang'),
    url(r'^layanan/sipa-sumur-bor$', 'izin.views.layanan_sipa_sumur_bor', name='layanan_sipa_sumur_bor'),
    url(r'^layanan/sipa-sumur-pasak$', 'izin.views.layanan_sipa_sumur_pasak', name='layanan_sipa_sumur_pasak'),
    url(r'^layanan/izin-pertambangan$', 'izin.views.layanan_pertambangan', name='layanan_pertambangan'),
    url(r'^layanan/tdp-pt$', 'izin.views.layanan_tdp_pt', name='layanan_tdp_pt'),
    url(r'^layanan/tdp-cv$', 'izin.views.layanan_tdp_cv', name='layanan_tdp_cv'),
    url(r'^layanan/tdp-firma$', 'izin.views.layanan_tdp_firma', name='layanan_tdp_firma'),
    url(r'^layanan/tdp-perorangan$', 'izin.views.layanan_tdp_perorangan', name='layanan_tdp_perorangan'),
    url(r'^layanan/tdp-koperasi$', 'izin.views.layanan_tdp_koperasi', name='layanan_tdp_koperasi'),
    url(r'^layanan/tdp-bul$', 'izin.views.layanan_tdp_bul', name='layanan_tdp_bul'),
    url(r'^layanan/tdp-cabang$', 'izin.views.layanan_tdp_baru_cabang', name='layanan_tdp_cabang'),
    url(r'^layanan/tdp-daftar-ulang$', 'izin.views.layanan_tdp_daftar_ulang', name='layanan_tdp_daftar_ulang'),
    url(r'^layanan/reklame$', 'izin.views.layanan_reklame', name='layanan_reklame'),
    url(r'^layanan/pemakaian-kekayaan$', 'izin.views.layanan_kekayaan', name='layanan_kekayaan'),
    url(r'^layanan/penggilingan-padi-&-huller$', 'izin.views.layanan_huller', name='layanan_huller'),
    url(r'^layanan/imb-umum$', 'izin.views.layanan_imb_umum', name='layanan_imb_umum'),
    url(r'^layanan/imb-perumahan$', 'izin.views.layanan_imb_perumahan', name='layanan_imb_perumahan'),
    url(r'^layanan/imb-bupati$', 'izin.views.layanan_imb_bupati', name='layanan_imb_bupati'),
    url(r'^layanan/izin-prinsip-penanaman-modal$', 'izin.views.layanan_izin_prinsip_penanaman_modal', name='layanan_izin_prinsip_penanaman_modal'),
    url(r'^layanan/izin-prinsip-perluasan-penanaman-modal$', 'izin.views.layanan_izin_prinsip_perluasan_penanaman_modal', name='layanan_izin_prinsip_perluasan_penanaman_modal'),
    url(r'^layanan/izin-prinsip-perubahan-penanaman-modal$', 'izin.views.layanan_izin_prinsip_perubahan_penanaman_modal', name='layanan_izin_prinsip_perubahan_penanaman_modal'),
    url(r'^layanan/izin-usaha-dan-izin-usaha-perluasan-penanaman-modal$', 'izin.views.layanan_izin_usaha_dan_izin_usaha_perluasan_penanaman_modal', name='layanan_izin_usaha_dan_izin_usaha_perluasan_penanaman_modal'),
    url(r'^layanan/izin-usaha-perubahan-penanaman-modal$', 'izin.views.layanan_izin_usaha_perubahan_penanaman_modal', name='layanan_izin_usaha_perubahan_penanaman_modal'),
    url(r'^layanan/izin-usaha-penggabungan-penanaman-modal$', 'izin.views.layanan_izin_usaha_penggabunggan_penanaman_modal', name='layanan_izin_usaha_penggabunggan_penanaman_modal'),
    url(r'^cari-pengajuan-izin$', 'izin.views.cari_pengajuan', name='cari_pengajuan'),
    url(r'^layanan/siup/formulir$', 'izin.views.formulir_siup', name='formulir_siup'),
    url(r'^layanan/tdp-pt/formulir$', 'izin.views.formulir_tdp_pt', name='formulir_tdp_pt'),
    ]
